name: Build JAR with Maven and Oracle JDK 23

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Oracle JDK 23
      - name: Set up Oracle JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 23

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the JAR file with Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 5: Upload the JAR file as an artifact (optional)
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-app-jar
          path: target/*.jar
