name: Build and Deploy JAR

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # Build the project
      - name: Build with Maven
        run: mvn clean package

      # Create the executables folder if it doesn't exist
      - name: Create executables folder
        run: mkdir -p executables

      # Copy the JAR to the executables folder
      - name: Copy JAR to executables
        run: cp target/*.jar executables/

      # Push the JAR to the repository
      - name: Push executables to repository
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Add built JAR to executables folder"
          add: executables/*
