name: Build JAR with Maven and Oracle OpenJDK 23.0.1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Oracle OpenJDK 23.0.1
      - name: Set up Oracle OpenJDK 23.0.1
        uses: actions/setup-java@v3
        with:
          distribution: 'jdk'
          java-version: '23.0.1'
          architecture: 'x64'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # Step 4: Build the project
      - name: Build JAR
        run: mvn clean package

      # Step 5: Save the JAR as an artifact
      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: application-jar
          path: target/*.jar
